variable "vpc_id" {}
variable "fargate_cpu" {}
variable "fargate_memory" {}
variable "app_count" {}
variable "priv-sub-1-id" {}
variable "priv-sub-2-id" {}
variable "az1" {}
variable "az2" {}
variable "pub-sub-1-id" {}
variable "pub-sub-2-id" {}
variable "elearning_certificate_arn" {}
