variable "region" {}
variable "vpc-cidr-block" {}
variable "pub-sub-1-cidr-block" {}
variable "pub-sub-2-cidr-block" {}
variable "priv-sub-1-cidr-block" {}
variable "priv-sub-2-cidr-block" {}
variable "fargate_cpu" {}
variable "fargate_memory" {}
variable "app_count" {}
variable "domain_name" {}
variable "db_user" {}
variable "db_password" {}
#variable "certificate_arn" {}